### ISSUE TITLE
Desolator (a survivor from Tesla Trooper mod) bug from FlatItemBuff

### ISSUE THREAD

**Issue by Fue34** [kking117/RoR2-kking117Mods#22]
When FlatItemBuff mod installed, the desolator's special,  'Spread the Doom'. When both FlatItemBuff and TeslaTrooper mod are installed, irradiated enemies do not get damaged once per tick, but super rapidly.

Here is a video of what I mean
https://user-images.githubusercontent.com/108565936/208316349-9d982a3c-dbf8-4155-98b2-f0216d94ecc3.mp4

**Comment by kking117** [comment]
I suspect this is a compatibility issue with another mod. I'll need a log in order to troubleshoot this.

If you manually install mods without a manager it will be in your "BepInEx" folder and should be a file called "LogOutput.log".

If you are using r2modman, go to "Settings" -> "Locations" -> "Browse profile folder" and it will open up the file browser. Go into the "BepInEx" folder and it should be a file called "LogOutput.log".

**Comment by kking117** [comment]
Actually never mind, I think I found the problem.

**Comment by kking117** [comment]
Alright I've updated the mod to 1.14.3 that includes a potential fix to the problem. Please be sure to close this issue if it fixed the problem.

**Comment by Fue34** [comment]
awesome ill test it out

Thanks much!

**Comment by Fue34** [comment]
Works great now!
