### ISSUE TITLE
Lost Seer's Lenses

### ISSUE THREAD

**Issue by gaforb** [kking117/RoR2-kking117Mods#25]
Just wanted to say I thought the Lenses rework from 1.14.4 was actually pretty good. Would like to see it come back as a config option if it isn't too much work. On the other hand, I had some suggestions for simpler reworks below:

Idea 1: 
You could give it the Safer Spaces treatment and have it scale your crit chance up by 1% (+1% per stack) every few seconds, and reset the chance on a crit. so:
"Gain critical strike chance the longer you go without a critical strike.
"Gain 1% (+1% per stack) Critical Strike chance every second. Resets on each Critical Strike."

Idea 2: 
Have it give you 100% crit chance when you stop being Out of Combat, but reduce your crit chance by 5% every 1 (+1 per stack) crits until it provides no bonus. so:
"Gain +100% Critical Strike Chance when entering combat. Decreases with each Critical Strike.
"Gain +100% bonus Critical Strike chance when entering combat. Lose 5% of this chance after every 1 (+1 per stack) Critical Strikes."

Both these reworks are better than base lensmakers for characters that make fewer, stronger attacks, which is a good balance point in my opinion. In addition, they have fun synergy with items that bring you out of combat like the reworked Stealth Kit, and still affect other crit-chance items and abilities in an interesting way.

**Comment by kking117** [comment]
I removed it because the effect was more fitting as an uncommon than a common, also making a damage threshold proc is a pain because item related mods can trigger it with lower damage.

Both ideas from what I've tested work early on but in late game there's so many effects that could be a critical that they end up being wasted, even on heavy hitters. Also the main gimmick of Lost Seer's Lenses is that the player gives up a common way to gain critical chance.

As it stands I don't want to bring back the old effect unless I figure out a way to add a damage threshold proc that doesn't get messed up by other item related mods.
