### ISSUE TITLE
[WarBannerBuff] Bring back attack speed and movement speed configurations

### ISSUE THREAD

**Issue by MightyW0lf** [kking117/RoR2-kking117Mods#7]
Re-add the attack speed and movement speed configurations removed in the v3.0.0. With them, the mod could be used for buffing the War Banner while keeping the effect close to vanilla. Or it could be tuned down in favor of other buffs the mod provides. Why removing it if it was implemented, there were no problems with it and it was useful?

**Comment by kking117** [comment]
Those two settings were originally removed due to the way stats were altered by this mod which were flawed as I believe Spinel Tonic would cause problems with attack speed changes and the movement speed changes wouldn't adjust acceleration to match the new speed. Only after reading this I remembered that this update started using R2API's stat hooks now which should actually fix both these issues. From my testing it seems the stat hook works flawlessly for adjusting the attack and move speed bonuses of the War Banner so expect an update to include these settings again real soon.
